CREATE TABLE IF NOT EXISTS products(
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
    sku TEXT UNIQUE,
stock_quantity INTEGER NOT NULL DEFAULT 0,
threshold INTEGER NOT NULL DEFAULT 30,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT  now()
)