FROM golang:1.24.5-bookworm

# Set the working directory
WORKDIR /app

# Copy go mod files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install Air (live reloader)
RUN go install github.com/air-verse/air@latest


# Copy the rest of the source code
COPY . .

# Run with Air and custom config
CMD ["air", "-c", ".air.toml"]
