// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (product_id,alert_message,alert_type,status) VALUES ($1,$2,$3,$4) RETURNING  id, product_id, alert_message, alert_type, status, created_at
`

type CreateAlertParams struct {
	ProductID    pgtype.Int4
	AlertMessage string
	AlertType    string
	Status       string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ProductID,
		arg.AlertMessage,
		arg.AlertType,
		arg.Status,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AlertMessage,
		&i.AlertType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
