// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddProducts implements pgx.CopyFromSource.
type iteratorForAddProducts struct {
	rows                 []AddProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Sku,
		r.rows[0].StockQuantity,
		r.rows[0].Threshold,
	}, nil
}

func (r iteratorForAddProducts) Err() error {
	return nil
}

func (q *Queries) AddProducts(ctx context.Context, arg []AddProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"products"}, []string{"id", "name", "sku", "stock_quantity", "threshold"}, &iteratorForAddProducts{rows: arg})
}
