// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID        pgtype.UUID
	ProductID pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type Product struct {
	ID            int32
	Name          string
	Sku           pgtype.Text
	StockQuantity int32
	Threshold     int32
}
