// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProduct = `-- name: AddProduct :one
INSERT INTO products (id, name, sku, stock_quantity, threshold) VALUES ($1,$2,$3,$4,$5) RETURNING  id, name, sku, stock_quantity, threshold
`

type AddProductParams struct {
	ID            int32
	Name          string
	Sku           pgtype.Text
	StockQuantity int32
	Threshold     int32
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, addProduct,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.StockQuantity,
		arg.Threshold,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.StockQuantity,
		&i.Threshold,
	)
	return i, err
}
